"""Fix quotation items relationships

Revision ID: 58dc50467ab9
Revises: 3fa71e58e42c
Create Date: 2024-12-15 22:46:19.220669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dc50467ab9'
down_revision = '3fa71e58e42c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('products', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('quotation_items', sa.Column('quotation_id', sa.String(length=36), nullable=False))
    op.add_column('quotation_items', sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('quotation_items', sa.Column('org_id', sa.String(length=36), nullable=False))
    op.alter_column('quotation_items', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('quotation_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'quotation_items', 'quotations', ['quotation_id'], ['id'])
    op.create_foreign_key(None, 'quotation_items', 'organizations', ['org_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.alter_column('quotation_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quotation_items', 'product_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('quotation_items', 'org_id')
    op.drop_column('quotation_items', 'unit_price')
    op.drop_column('quotation_items', 'quotation_id')
    op.drop_column('products', 'updated_at')
    op.drop_column('products', 'created_at')
    # ### end Alembic commands ###