"""Make id column in organization autoincrement

Revision ID: 624003bfcc54
Revises: 58dc50467ab9
Create Date: 2024-12-15 23:00:23.142476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '624003bfcc54'
down_revision = '58dc50467ab9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organizations', 'id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False,
               autoincrement=True)
    # ### end Alembic commands ###